; SPDX-License-Identifier: GPL-3.0-or-later

;--------------------------------------------------------------
; TESTROUTINE for breakpoint
;--------------------------------------------------------------
monitor		equ	100h
conin		equ	103h
conout		equ	106h
out_byte	equ	109h
out_crlf	equ	10ch
out_word	equ	10fh
out_string	equ	112h
hex_to_bc	equ	115h

CR		equ	0Dh
LF		equ	0Ah

		org	1000h
test:
		ex	af, af'
		ld	a, 55h
		ld	i, a
		ex	af, af'
		ld	hl, 0
		xor	a
		ld	b, 5
test1:
		dec	a
		inc	hl
		call	test_sub
		nop
		nop
		djnz	test1

		call	out_word
		ld	hl, testready
		call	out_string
		jp	monitor

test_sub:
		rlca
		ret


testready:	db	CR, LF, "READY", CR, LF, 0
